steps:
  - label: ":js:"
    plugins:
      - docker#v3.5.0:
          image: node:12-alpine
      - artifacts#v1.3.0:
          upload: artifact-test.txt
          # upload: node_modules.tar.gz
    commands:
      - sh ./.buildkite/test-and-lint.sh

  - label: "Test artifact"
    plugins:
      - artifacts#v1.3.0:
          download: artifact-test.txt
    commands:
      - cat artifact-test.txt
  # - label: ":cypress:"
  #   plugins:
  #     - docker-compose#v3.3.0:
  #         run: cypress
