steps:
  - label: ':js:'
    plugins:
      #   - docker#v3.5.0:
      #       image: node:12-alpine
      - artifacts#v1.3.0:
          upload: coverage/lcov.info
          # upload: artifact-test.txt
          # upload: node_modules.tar.gz
    commands:
      - sh ./.buildkite/test-and-lint.sh
  # - label: ":cypress:"
  #   plugins:
  #     - docker-compose#v3.3.0:
  #         run: cypress
