steps:
  - label: ":js:"
    plugins:
      - docker#v3.5.0:
          image: node:12-alpine
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    commands:
      - sh ./.buildkite/test-and-lint.sh
