steps:
  - label: ':js:'
    plugins:
      - docker#v3.5.0:
          image: node:12-alpine
      - artifacts#v1.3.0:
          upload: coverage/lcov.info
          # upload: artifact-test.txt
          # upload: node_modules.tar.gz
    commands:
      - mkdir coverage && echo 'end_of_record' > coverage/lcov.info
      # - sh ./.buildkite/test-and-lint.sh

  - label: ':coverage: Coveralls'
    plugins:
      - docker#v3.5.0:
          image: node:12-alpine
      - artifacts#v1.3.0:
          download: coverage/lcov.info
    commands:
      - yarn coveralls
    # command: cat coverage/lcov.info
  # - label: ":cypress:"
  #   plugins:
  #     - docker-compose#v3.3.0:
  #         run: cypress
